version: '3'

services:
  node:
    container_name: api_slido
    image: node:16
    cpus: 0.3
    mem_limit: 5g
    working_dir: /app
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - MYSQL_HOST=database
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=slido_db
    depends_on:
      - database
  database:
    container_name: db_slido
    image: mysql:8.0.32
    cpus: 0.4
    mem_limit: 6g
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306